In [7]:
import numpy as np

def feautrier_method(mu_values):
    # Given parameters
    deltau = 0.1

    # Optical depth grid
    tau = np.linspace(0, 0.5, 6)
    num_angles = len(mu_values)

    # Initialize the solution matrix
    u_matrix = np.zeros((len(tau), num_angles))

    for j, mu in enumerate(mu_values):
        # Precomputed values
        mu2 = mu**2
        dt2 = deltau**2

        a = mu2/dt2
        d = 1 + 2*mu2/dt2
        c = mu2/dt2

        evals = np.zeros(len(tau))

        # Given function for b(tau)
        def b(tau):
            return (3/4) * 1 * (tau + 2/3)

        # Calculate values for each tau using the function b(tau)
        for i in range(len(tau)):
            evals[i] = b(tau[i])

        # Additional coefficients
        d0 = 1 + (mu/deltau) + (deltau/(2*mu))
        c0 = mu/deltau

        e0 = (evals[0]*deltau)/(2*mu)
        e5 = (evals[5]*(0.5 + (mu/deltau)) + evals[4]*(0.5 - (mu/deltau)))
        d5 = 0.5 + (mu/deltau)
        a5 = (mu/deltau) - 0.5

        # Construct the matrix x
        x = np.array([[d0, -c0, 0, 0, 0, 0],
                      [-a, d, -c, 0, 0, 0],
                      [0, -a, d, -c, 0, 0],
                      [0, 0, -a, d, -c, 0],
                      [0, 0, 0, -a, d, -c],
                      [0, 0, 0, 0, -a5, d5]])

        # Construct the vector s
        s = np.array([e0, evals[1], evals[2], evals[3], evals[4], e5])

        # Solve the system of linear equations
        u_matrix[:, j] = np.linalg.solve(x, s)

    return u_matrix

# Example: For multiple angles
mu_values = np.array([0.1, 0.5, 0.9])
u_matrix_example = feautrier_method(mu_values)

# Print the solution matrix
print("Solution matrix for mu values:", mu_values)
print(u_matrix_example)

Solution matrix for mu values: [0.1 0.5 0.9]
[[0.29934426 0.43768125 0.58740778]
 [0.49836066 0.52397112 0.65321486]
 [0.6207377  0.60821984 0.71998756]
 [0.71385246 0.69079736 0.78762431]
 [0.79581967 0.77200677 0.85603419]
 [0.87360656 0.85209645 0.92513585]]


In [6]:
u_example = feautrier_method(-mu)
print("Solution vector for mu =", -mu)
print(u_example)

Solution vector for mu = -0.5773502691896257
[ 0.03849918  0.02490842 -0.0051851  -0.05493416 -0.12808126 -0.22907079]
